---

- hosts: all
  become: true
  tasks:

  - name: install apache and php on Red Hat
    package:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

